### ISSUE TITLE
Format the date and time inputs

### ISSUE THREAD

**Issue by SamanthaLFreeman** [Search-and-Rescue/SearchAndRescue-FE#115]
As a developer
I want to the user to know exactly how to format the date and time inputs
so that the information is saved correctly in the database

Input in Trip:
- [x] startDate (ex: "May 1, 2020")
- [x] startTime (ex:  "08:00")
- [x] endDate (ex: "May 3, 2020")
- [x] endTime (ex: "22:00")
- [x] notificationDate (ex: "May 4, 2020")
- [x] notificationTime (ex: "15:00")

**Comment by kawilliams8** [comment]
This is temporarily achieved through the placeholder text, but a calendar picker would be a very nice update.
